package com.linju.framework.mapper;

import com.linju.framework.model.WechatDemo;

public interface WechatDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    int insert(WechatDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    int insertSelective(WechatDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    WechatDemo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WechatDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WechatDemo record);
}